### ISSUE TITLE
Resolving block IDs in bccm

### ISSUE THREAD

**Issue by CodesByChris** [gi0na/r-ghypernet#15]
When printing `bccm` fits, the entries of the block-Omega matrix are printed in a list. There, pairs of blocks are enumerated as a cryptic number that is difficult to interpret in terms of the block assignment vector that the user has passed when fitting the `bccm`. The function internally represents each block by a prime number and creates the enumeration of the block-pairs as the product of the two primes of the involved blocks. However, the user usually doesn't know which prime number is assigned to which block.

For example:
```r
library(ghypernet)

data("adj_karate")
data("vertexlabels")

bccm(adj = adj_karate, labels = vertexlabels, directed = FALSE, selfloops = FALSE)
```
which prints
```
...
Coefficients:
    Estimate    Std.Err t value    Pr(>t)    
1 1.00000000 0.00000000     Inf < 2.2e-16 ***
2 0.09044494 0.00021692  416.95 < 2.2e-16 ***
4 0.91049902 0.00040434 2251.79 < 2.2e-16 ***
...
```

Can the output state the block labels instead of the prime products (1, 2, 4) to identify the pairs? For example, something like
```
1:1
1:2
2:2
```
where 1 and 2 are the block-labels from `vertexlabels`.

**Comment by gi0na** [comment]
Added new functionality to address issue
